# Визуализация данных

© Гошин Е.В., доцент кафедры технической кибернетики, к.т.н., Самарский университет  
© Петров М.В., старший преподаватель кафедры киберфотоники, Самарский университет

# Лекция 5. Библиотека `Plotly`

## Содержание

1. [Введение](#51-введение)
2. [Создание графиков с использованием `Plotly Express`](#52-создание-графиков-с-использованием-plotly-express)
3. [Анимации в `Plotly Express`](#53-анимации-в-plotly-express)
4. [Создание графиков с использованием `Plotly Graph Objects`](#54-создание-графиков-с-использованием-plotly-graph-objects)
5. [Экспорт в растровый и векторный форматы](#55-экспорт-в-растровый-и-векторный-форматы)
6. [Пример](#56-пример)
7. [`Plotly Dash`](#57-plotly-dash)

## 5.1 Введение

`Plotly` &ndash; это набор открытых библиотек для создания интерактивных графиков. В отличие от статичных изображений, графики `Plotly` реагируют на действия пользователя: всплывающие подсказки, панорамирование и масштабирование и многое другое. Библиотеки `Plotly` доступны на Python, а также на ряде других языков программирования, включая `R` и `Julia`. Доступен широкий спектр графиков: от статистических и научных до финансовых и географических. Визуализации можно отображать разными способами, например, в Jupyter-ноутбуках, HTML-файлах и веб-приложениях, создаваемых с помощью фреймворка `Plotly Dash`. Статические (неинтерактивные) графики можно экспортировать как растровые или векторные изображения.

> `R` &ndash; интерпретируемый язык программирования и среда разработки для статистического анализа, обработки и визуализации данных: [The R Project for Statistical Computing](https://www.r-project.org/).  
> `Julia` &ndash; высокоуровневый язык программирования с динамической типизацией, созданный для математических вычислений: [The Julia Programming Language](https://julialang.org/).

### `Plotly Express` vs. `Plotly Graph Objects` vs. `Plotly Dash`

Чтобы эффективно использовать `Plotly`, важно понимать различия между `Plotly Express`, `Plotly Graph Objects` и `Plotly Dash`.

По сути, это три отдельные (хотя и пересекающиеся) модуля `Plotly` со своими сценариями использования:

- `Plotly Express` (`plotly.express`, как правило импортируется как `px`) &ndash; доступный высокоуровневый интерфейс для создания визуализаций, предлагающий порядка 30 типов графиков. Модуль предоставляет функции, позволяющие создавать графики одной строкой кода. Поскольку это высокоуровневый интерфейс, при использовании `plotly.px` не нужно напрямую взаимодействовать с низкоуровневой структурой графа. `Plotly` рекомендует начинать с `Express`, прежде чем переходить к `Graph Objects`.
- `Plotly Graph Objects` (`plotly.graph_objects`, обычно импортируется как `go`) &ndash; это сами графики, которые `Plotly` создает и рендерит: когда мы формируем график через `plotly.px`, `Plotly` генерирует объект *«Graph Object»* для хранения данных графика. Туда входят и данные визуализации, и атрибуты (цвета, размеры, формы и т.п.). Поэтому мы можем строить визуализации и на нижнем уровне &ndash; через `plotly.go`; фактически всё, что можно сделать в `plotly.px`, можно воссоздать в `plotly.go`. Как правило, рекомендуется использовать `plotly.px`, когда это возможно, поскольку `plotly.go` часто требует больше кода. Однако, у `plotly.go` есть важные частные случаи применения.
- Модуль `Plotly Dash` (import dash) &ndash; это фреймворк для создания интерактивных веб-приложений (обычно дашбордов), которые можно встраивать в сайты и другие платформы. Часто фигуры из `plotly.px` и/или `plotly.go` интегрируются в приложения `Dash`, формируя полный стек `Plotly` для создания, обработки и публикации интерактивных визуализаций данных. `Plotly Dash` построен поверх `React.js` и `Plotly.js`, что позволяет интегрироваться с вебом без знания JavaScript, CSS или HTML &ndash; достаточно Python.

`Plotly` предоставляет подробную документацию по работе с Express и Graph Objects и по использованию Dash.

### Почему Plotly?

В экосистеме Python доступно множество библиотек для построения графиков: `Matplotlib`, `Seaborn`, `Bokeh`, `Pygal` и др. При таком выборе возникает необходимость остановиться на одной из них. Здесь важны сценарий использования, стилистические предпочтения и простота работы: у каждой библиотеки есть свои достоинства. Некоторые заметные преимущества `Plotly`:
- `Plotly` &ndash; одна из немногих библиотек, ориентированных на интерактивные графики: например, `Matplotlib` и `Pygal` предлагают ограниченную интерактивность (`Bokeh` также ориентирован на интерактивность и является жизнеспособной альтернативой).
- `Plotly` &ndash; пакет для Python, который одновременно упрощает создание графиков и их интеграцию в веб-приложения.
- У `Plotly` бесшовная интеграция с `pandas` (в частности, `DataFrame` можно напрямую передавать в графические объекты).
- Поддерживаются интерактивные 3D-графики (как правило, недоступные в других библиотеках).
- `Plotly` прост в использовании (например, добавление анимации и выпадающих списков &ndash; относительно простая операция).

Источники:
 - [Open Source Python Graphing and Data Visualization Library](https://plotly.com/python/)

## 5.2 Создание графиков с использованием `Plotly Express`

Источники:
 - [Plotly Express in Python](https://plotly.com/python/plotly-express/)
 - [Plotly Python Open Source Graphing Library Basic Charts](https://plotly.com/python/basic-charts/)
 - [Bar Charts in Python](https://plotly.com/python/bar-charts/)
 - [Line Charts in Python](https://plotly.com/python/line-charts/)
 - [Scatter Plots in Python](https://plotly.com/python/line-and-scatter/)

Импортируем модули:

In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
plotly.__version__

'7.1.0'

Далее импортируем набор данных (чаевые официанту в ресторане):

In [2]:
df_tips = px.data.tips()
df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Столбчатые диаграммы

> Документация с примерами: [Bar Charts in Python](https://plotly.com/python/bar-charts/).

Теперь, когда у нас есть `DataFrame`, начнём с базовых графиков в `Plotly Express`. Построим столбчатую диаграмму количества чаевых по дню посещения. Поскольку исходный набор не содержит заранее посчитанных количеств (каждая строка &ndash; одно посещение), сначала создадим новый `DataFrame` с группировкой по дню и с подсчётом количества:

In [3]:
df_tips_by_day = df_tips.groupby(["day"], as_index=False).size()
df_tips_by_day

    day  size
0   Fri    19
1   Sat    87
2   Sun    76
3  Thur    62

Далее создадим столбчатую диаграмму с использованием `df_by_day`. Заметим, что график сохраняется в переменную `fig` &ndash; это распространённая практика в `Plotly`:

In [4]:
fig = px.bar(df_tips_by_day, x="day", y="size")
fig.show()

Итак, мы построили первый график с `px`. Обратим внимание, что интерактивность уже доступна: при наведении на столбец показываются день и количество посещений. Кроме того, в правом верхнем углу можно сохранить график (как статичное изображение) через иконку камеры в .png. Здесь же доступны масштабирование, панорамирование, авто-масштаб и сброс вида. Эти функции применимы ко всем визуализациям в `Plotly`.  

Однако, визуально график можно улучшить: добавить заголовок, цвета и более понятную подпись оси $Y$. Всё это можно сделать при создании графика, передав дополнительные аргументы методу `.bar()`. Используем `labels`, чтобы заменить подпись «size» на «Count», и `color`, чтобы раскрасить столбцы по переменной (здесь &ndash; по типу «day»). Добавим заголовок &ndash; аргумент `title`.

In [5]:
fig = px.bar(
    df_tips_by_day,
    x="day",
    y="size",
    title="Tips per day count",
    labels={"size": "Count"},
    color="day",
)

fig.show()

Как видно, `Plotly` автоматически добавляет легенду при делении по цвету (при желании это можно отключить). Легенда интерактивна: один щелчок по элементу скрывает его, двойной &ndash; изолирует (скрывает все кроме текущего).

### Линейные графики

> Документация с примерами: [Line Charts in Python](https://plotly.com/python/line-charts/).

Перейдём к линейному графику. Общее правило: графики `Plotly Express` создаются как `px.somegraph()`, где `somegraph` &ndash; целевой тип. Ранее мы использовали `px.bar()` для столбчатой диаграммы; теперь используем `px.line()` для линии. Нужный термин для каждого типа графика можно найти в документации `Plotly`.

Возьмём другой датасет для визуализации («Life Expectancy at Birth» &ndash; *ожидаемая продолжительность жизни при рождении*):

In [6]:
df_pop = px.data.gapminder()
df_pop.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

Построим график изменения cредней продолжительности жизни по годам и континентам. Создадим `DataFrame` с группировкой по году и континенту:

In [7]:
df_pop_by_year = df_pop.groupby(["continent", "year"],as_index=False)['lifeExp'].mean()
df_pop_by_year.head()

  continent  year    lifeExp
0    Africa  1952  39.135500
1    Africa  1957  41.266346
2    Africa  1962  43.319442
3    Africa  1967  45.334538
4    Africa  1972  47.450942

Создадим линейный график методом `.line()`, добавим форматирование через `labels` и `color`. При желании раскомментируем title:

In [8]:
fig = px.line(
    df_pop_by_year,
    x="year",
    y="lifeExp",
    title="Mean life expectancy per year",
    labels={"lifeExp": "Life Expectancy"},
    color="continent",
)

fig.show()

`Plotly Express` предоставляет возможность изменения отображения уже построенного графика: метод `.update_layout()` у объекта `fig`. Этот метод подходит к любому графику `Plotly Express` и принимает широкий набор параметров. В качестве примера обновим семейство шрифтов, цвета шрифтов и заголовок:

In [9]:
fig.update_layout(
    font_family="Courier New",  # Update font
    font_color="blue",  # Make font blue
    legend_title_font_color="red"  # Make legend title red
)

fig.show()

### Диаграммы рассеяния

> Документация с примерами: [Scatter Plots in Python](https://plotly.com/python/line-and-scatter/).

Диаграммы рассеяния часто используют для визуализации связей между непрерывными переменными; в нашем наборе данных можно взглянуть на связь суммы чека и чаевых:

In [10]:
fig = px.scatter(
    df_tips,
    x="total_bill",
    y="tip",
    color="sex",
    title="Tips in bill"
)
fig.show()

### Фасетные графики

> Документация с примерами: [Facet and Trellis Plots in Python](https://plotly.com/python/facet-plots/).

Фасетные графики состоят из нескольких подграфиков, которые:
 - разделяют оси;
 - показывают подмножества данных по тем же переменным.  

 В `Plotly Express` их можно построить очень просто. Сначала, как и выше, укажем, какой тип графика использовать в подграфиках. Далее параметр `facet_col` задаёт переменную для разбиения данных на подграфики.

In [11]:
# Группируем по признакам «курения», «времени» и «дню» и считаем средний чек
df_tips_by_parameters = df_tips.groupby(
    ["smoker", "time", "day"], as_index=False
)['total_bill'].mean()

df_tips_by_parameters.head()

  smoker    time   day  total_bill
0     No  Dinner   Fri   19.233333
1     No  Dinner   Sat   19.661778
2     No  Dinner   Sun   20.506667
3     No  Dinner  Thur   18.780000
4     No   Lunch   Fri   15.980000

In [12]:
fig = px.bar(
    df_tips_by_parameters,
    x="smoker",
    y="total_bill",
    facet_col="time",
    facet_row="day", 
    color="smoker",
    title="Total bill",
)
fig.show()

Поменяем `facet_col` и `facet_row` местами:

In [13]:
fig = px.bar(
    df_tips_by_parameters,
    x="smoker",
    y="total_bill",
    facet_col="day",
    facet_row="time", 
    color="smoker",
    title="Total bill",
)
fig.show()

Заметим, что этот подход не требует указывать размеры сетки &ndash; `Plotly Express` автоматически делит сетку по количеству категорий (здесь $4 \times 2$). Однако метод подходит для фигуры с одним типом графика. Как создавать фигуры с заданными размерами и несколькими разными типами графиков, мы разберём в разделе про `Graph Objects`.

Еще один пример из документации:

In [14]:
fig = px.line(df_pop[df_pop.continent == 'Africa'], x="year", y="lifeExp", facet_col="country", facet_col_wrap=8,
              facet_row_spacing=0.04, # default is 0.07 when facet_col_wrap is used
              facet_col_spacing=0.04, # default is 0.03
              height=600, width=800,
              title="Life Expectancy in Africa")
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
fig.update_yaxes(showticklabels=True)
fig.show()

## 5.3 Анимации в `Plotly Express`

> Документация с примерами: [Intro to Animations in Python](https://plotly.com/python/animations/).

Графики `Plotly Express` уже обладают встроенной интерактивностью. Однако мы можем добавить и другие элементы, включая анимационные кадры.  
Анимационный кадр отображает, как данные меняются относительно некоторой величины. В исторических исследованиях такая величина &ndash; чаще всего время, но также подойдут и другие числовые переменные с упорядочиваемостью (например, порядковые/интервальные). Фигура с анимацией содержит интерактивную панель, позволяющую воспроизводить/останавливать анимацию и вручную перемещаться по шкале.  

Чтобы создать фигуру с анимацией, действуем как раньше: указываем тип графика, затем в соответствующем вызове добавляем параметр `animation_frame` для выбора переменной изменения.

In [15]:
fig = px.bar(
    df_pop,
    x="country",
    y="pop",
    color="continent",
    animation_frame="year", 
    title="Animated population per year"
)
fig.show()

Пример из документации:

In [16]:
fig = px.scatter(
    df_pop,
    x="gdpPercap",
    y="lifeExp",
    animation_frame="year",
    animation_group="country",
    size="pop",
    color="continent",
    hover_name="country",
    log_x=True,
    size_max=55,
    range_x=[100,100000],
    range_y=[25,90]
)
fig.show()

### Добавление анимаций: выпадающие списки (Dropdown menus)

Выпадающие списки чуть сложнее, чем кадры анимации. Они позволяют переключать множество параметров отображения: цвета, линии, оси и даже переменные. При создании фигур с dropdown-списками сначала сформируем исходный график без выпадающего списка (это первое представление для пользователей).

In [17]:
fig = px.scatter(
    df_tips,
    x="total_bill",
    y="tip",
    color="day",
    category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun']},
    title="Заголовок",
)
fig.show()

Алгоритм таков:
- обращаемся к параметру `updatemenus` &ndash; это список словарей с метаданными дизайна
- нас интересует выпадающий список, который находится внутри ключа `buttons`
- `buttons` хранит список словарей, каждый &ndash; опция выпадающего списка
- создадим пять кнопок для разных дней
- каждый словарь кнопки должен иметь ключи: `args` (что менять), `label` (текст в выпадающем списке), `method` (как изменять: `update`/`restyle`/`animate` и т.д.).

Под капотом `args` включает список словарей: первый управляет видимостью данных (`visible` &ndash; список булевых флагов по индексам слоёв/трейсов), второй &ndash; заголовком и подписями осей (опционально). В нашем примере данные разбиты на четыре группы, поэтому у `visible` четыре элемента. Для первой кнопки (все) укажем `[True, True, True, True]`, для остальных &ndash; `True` только у соответствующей категории.

> Подробнее в [Python Figure Reference: layout.updatemenus](https://plotly.com/python/reference/layout/updatemenus/).

In [18]:
fig.update_layout(
    updatemenus=[
        dict(
            buttons=list(
                [  # Create the 'buttons' list to store a dictionary for each dropdown option
                    dict(
                        label="Все дни",  # Add label for first 'view'
                        method="update",
                        args=[
                            {
                                "visible": [True, True, True, True]
                            },  
                            {
                                "title": "Зависимость чаевых от чека",
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),
                    dict(
                        label="Четверг",  # Add label for second 'view'
                        method="update",
                        args=[
                            {
                                "visible": [True, False, False, False]
                            },  
                            {
                                "title": "Зависимость чаевых от чека в четверг",  # Can change titles here to make the graph more dynamic
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),  # As above
                    dict(
                        label="Пятница",  # Add label for third 'view'
                        method="update",
                        args=[
                            {
                                "visible": [False, True, False, False]
                            },  
                            {
                                "title": "Зависимость чаевых от чека в пятницу",  # New title
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),
                    dict(
                        label="Суббота",  # Add label for fourth 'view'
                        method="update",
                        args=[
                            {
                                "visible": [False, False, True, False]
                            },  
                            {
                                "title": "Зависимость чаевых от чека в субботу",  # New title
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),
                    dict(
                        label="Воскресенье",  # Add label for fourth 'view'
                        method="update",
                        args=[
                            {
                                "visible": [False, False, False, True]
                            },  
                            {
                                "title": "Зависимость чаевых от чека в воскресенье",  # New title
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),
                    dict(
                        label="Выходные",  # Add label for fourth 'view'
                        method="update",
                        args=[
                            {
                                "visible": [False, False, True, True]
                            },  
                            {
                                "title": "Зависимость чаевых от чека в выходные",  # New title
                                "xaxis": {"title": "Сумма чека"},
                                "yaxis": {"title": "Сумма чаевых"},
                            },
                        ],
                    ),
                ]
            )
        )
    ]
)

fig.show()

Создание выпадающего списка даёт пользователю удобный способ изолировать интересующую категорию и одновременно позволяет формировать динамические заголовки и подписи, зависящие от выбранной опции.  
Теперь перейдём к `Plotly Graph Objects`: что это такое, как они устроены и когда/почему стоит использовать `plotly.go` вместо `plotly.px`.

## 5.4 Создание графиков с использованием `Plotly Graph Objects`

> Источники:
>  - [API &rarr; plotly.graph_objects: low-level interface to figures, traces and layout](https://plotly.com/python-api-reference/plotly.graph_objects.html).

Чтобы начать, импортируем модуль `graph_objects`:

In [19]:
import plotly.graph_objects as go

### Структура данных `Graph Objects`

Как отмечалось во введении, все фигуры `Plotly Express` на самом деле представляют собой `Graph Objects`. То есть, создавая фигуру через `plotly.px`, мы получаем экземпляр `Graph Object`.  
Это можно увидеть, если проверить тип переменной `fig`:

In [20]:
type(fig)

plotly.graph_objs._figure.Figure

Итак, все фигуры `Plotly` &ndash; это `Graph Objects`.

Структура `Graph Objects` &ndash; древовидная (иерархическая), с тремя верхними уровнями: `data`, `layout` и `frames`:
- `data`: тип графика, категории, точки данных, видимость в легенде, типы маркеров, содержимое всплывающих подсказок и т.п.
- `layout`: размеры фигуры, шрифты и цвета, аннотации, координаты подплотов, метаданные кнопок (см. пример выше), фоновые изображения.
- `frames`: информация для анимаций &ndash; какие данные показывать на каждом кадре ползунка. Атрибут создаётся только при наличии анимации.

Просматривать структуру удобно через словарь: `fig.to_dict()` или в JSON &ndash; `fig.to_json(pretty=True)`. Ниже пример вывода первых 500 символов:

In [21]:
print(fig.to_json(pretty=True)[0:500] + "\n...")

{
  "data": [
    {
      "hovertemplate": "day=Thur\u003cbr\u003etotal_bill=%{x}\u003cbr\u003etip=%{y}\u003cextra\u003e\u003c\u002fextra\u003e",
      "legendgroup": "Thur",
      "marker": {
        "color": "#636efa",
        "symbol": "circle"
      },
      "mode": "markers",
      "name": "Thur",
      "orientation": "v",
      "showlegend": true,
      "x": {
        "dtype": "f8",
        "bdata": "MzMzMzMzO0DD9Shcj8I2QArXo3A9SjFAcT0K16NwM0ApXI\u002fC9agwQKRwPQrXIyRA16NwPQpXQED2KFyPwvUvQ
...

Анализ структуры помогает понять внутреннее устройство. Если вывести полностью, мы увидим, что:
- атрибут `data` хранит данные по категориям в отдельных словарях
- атрибут `data` указывает тип графика (например, `scatter`)
- атрибут `layout` хранит заголовок фигуры
- атрибут `layout` содержит данные кнопок (выпадающее меню)
- атрибута `frames` нет, если у фигуры нет анимации

### `Plotly Graph Objects` vs `Plotly Express`

> Важно: создание графиков через `plotly.go` обычно требует больше кода, чем через `plotly.px`.

Рассмотрим пример: построим горизонтальную столбчатую диаграмму «средний GDP по континентам». Сначала создадим `DataFrame`:

In [22]:
df_pop_gdp_continent=df_pop.groupby(["continent"], as_index=False)['gdpPercap'].mean()
df_pop_gdp_continent.head()

  continent     gdpPercap
0    Africa   2193.754578
1  Americas   7136.110356
2      Asia   7902.150428
3    Europe  14469.475533
4   Oceania  18621.609223

Теперь построим график в `plotly.go`:

In [23]:
fig = go.Figure(
    go.Bar(x=df_pop_gdp_continent["gdpPercap"],
           y=df_pop_gdp_continent["continent"],
    orientation='h', 
    hovertemplate="Континент=%{y}<br>Средний ВВПP=%{x}<extra></extra>"), # Need to format hover text (this is automatic with plotly.px)
    layout={
                "title": "Средний ВВП",
                "title_x": 0.5,
                "title_xanchor": "center"
            }
)
fig.update_layout(  # Need to use .update_layout to add x- and y-axis labels (this is automatic with plotly.px)
    xaxis=dict(title="Средний ВВП"), 
    yaxis=dict(title="Континент"))

fig.show()

Для выравнивания заголовка графика по центру необходимо указать:
 - `title_x`: относительная координата положения «якоря» заголовка по оси $X$ ($0.5$ &ndash; «середина»)
 - `title_xanchor`: выравнивание по оси $X$ относительно «якоря» (`auto`/`left`/`center`/`right`)  

Аналогичные параметры можно задать и для оси $Y$.  
Подробнее:
 - [Python Figure Reference: layout &rarr; title &rarr; x](https://plotly.com/python/reference/layout/#layout-title-x)
 - [Python Figure Reference: layout &rarr; title &rarr; xanchor](https://plotly.com/python/reference/layout/#layout-title-xanchor)
 - [Python Figure Reference: layout &rarr; title &rarr; y](https://plotly.com/python/reference/layout/#layout-title-y)
 - [Python Figure Reference: layout &rarr; title &rarr; yanchor](https://plotly.com/python/reference/layout/#layout-title-yanchor)

 Сделаем тот же график в `plotly.px`:

In [24]:
fig = px.bar(
    df_pop_gdp_continent,
    x="gdpPercap",
    y="continent",
    orientation="h",
    labels={
                "gdpPercap": "Средний ВВП",
                "continent": "Континент"
            },
    title="Средний ВВП"
)

fig.update_layout(title_x=0.5, title_xanchor="center")

fig.show()

Вывод: `plotly.go` требует больше кода, так как многие элементы нужно задавать вручную. Поэтому, если возможно, лучше использовать `plotly.px`.

### Зачем использовать `Graph Objects`?

Возникает вопрос: если с `plotly.px` проще, зачем `plotly.go`? Краткий ответ: ряд функций доступен только через `plotly.go`. Рассмотрим две из них: таблицы и подграфики.

### Таблицы

Одна из полезных возможностей `plotly.go` &ndash; аккуратные интерактивные таблицы.  

Шаги:
 - создаём фигуру `.Figure()`
 - в атрибуте `data` вызываем `.Table()`, чтобы задать тип «таблица»;
 - в `.Table()` формируем словарь `header` со списком заголовков столбцов
 - туда же &ndash; словарь `cells` для данных (`values`)

Можно настраивать подписи, цвета и выравнивание.  
Создадим таблицу для всего набора данных:

In [25]:
fig = go.Figure(
    data=[
        go.Table(  # Создаем таблицу
            header=dict(
                values=list(
                    df_pop.columns
                ),  # Получаем список всех столбцов DataFrame 'df_pop' для заголовка
                fill_color="paleturquoise",  # Цвет фона заголовка таблицы
                align="center",  # Выравнивание текста в заголовке
            ),
            cells=dict(
                values=df_pop.transpose().values.tolist(),  # Получаем значения из датафрейма
                fill_color="lavender",
                align="left",
            ),
        )
    ]
)

fig.show()

Как и в `px`, фигуры `go` обладают встроенной интерактивностью. Таблицы можно пролистывать. Столбцы можно перетаскивать за заголовки.

### Подграфики (`Subplots`)

Другая возможность `plotly.go` &ndash; построение подграфиков. Хотя `plotly.px` строит панельные графики, они ограничены *единым типом* графика/осей/переменных. Подграфики позволяют создать сетку с *разными типами графиков*, своими осями и переменными &ndash; фактически мини-дашборд.
Код достаточно длинный, поэтому выполним пошагово. Построим сетку 1×3 с тремя графиками: слева &ndash; столбчатая, посередине &ndash; линия, справа &ndash; `boxplot`.  

#### Шаг 1. Импортируем модуль подплотов и готовим данные

In [26]:
from plotly.subplots import make_subplots

df_pop_asia, df_pop_europe = (
    df_pop.loc[df_pop["continent"] == "Asia"],
    df_pop.loc[df_pop["continent"] == "Europe"],
)
df_pop_asia_year, df_pop_europe_year = (
    df_pop_asia.groupby(["year"], as_index=False)['pop'].sum(),
    df_pop_europe.groupby(["year"], as_index=False)['pop'].sum(),
)

#### Шаг 2. Создадим пустую сетку 1×3 через `make_subplots()`

In [27]:
fig = make_subplots(rows=1, cols=3)

#### Шаг 3. Добавим первый график (столбчатый) методом `.add_trace()`

In [28]:
fig.add_trace(
    go.Bar(
        x=df_pop_gdp_continent[
            "continent"
        ],
        y=df_pop_gdp_continent["gdpPercap"],
        name="Average GDP",
        hovertemplate="<b>Continent=</b> %{x}<br><b>GDP=</b> %{y}<extra></extra>",
    ),
    # В явном виде можно задать положение субграфика
    row=1,
    col=1
)

#### Шаг 4. Добавим второй график (линейный)

In [29]:
fig.add_trace(
    go.Line(
        x=df_pop_asia_year[
            "year"
        ],
        y=df_pop_asia_year["pop"],
        name="Asia",  # Эта линия — Азия
        hovertemplate="<b>Continent=</b>Asia<br><b>Year=</b> %{x}<br><b>Total population=</b> %{y}</b><extra></extra>",
    ),
    row=1,
    col=2,
)

fig.add_trace(
    go.Line(
        x=df_pop_europe_year["year"],
        y=df_pop_europe_year["pop"],
        name="Europe",  # Эта линия — Европа
        hovertemplate="<b>Continent=</b>Europe<br><b>Year=</b> %{x}<br><b>Total population=</b> %{y}</b><extra></extra>",
    ),
    row=1,
    col=2,
)

c:\Users\UD\ait-ds\Lib\site-packages\plotly\graph_objs\_deprecations.py:378: DeprecationWarning: plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.

  warnings.warn(

> Если не импортировать `plotly.graph_objs.scatter.Line`, может появиться `DeprecationWarning` &ndash; его можно игнорировать.

#### Шаг 5. Добавим третий график (`boxplot`)

In [30]:
fig.add_trace(
    go.Box(
        y=df_pop_asia["lifeExp"], name="Asia"
    ),
    row=1,
    col=3,
)

fig.add_trace(go.Box(y=df_pop_europe["lifeExp"], name="Europe"), row=1, col=3)

#### Шаг 6. Отформатируем фигуру

In [31]:
fig.update_layout(
    font_family="Times New Roman",  # Шрифт для фигуры
    hoverlabel_font_family="Times New Roman",  # Шрифт для текста в подсказках
    hoverlabel_font_size=16,  # Размер шрифта для текста в подсказках
    title_text="Население и ВВП",
    title_x=0.5,
    xaxis1_title_text="Континент",  # Подпись оси X 1-го субграфика
    yaxis1_title_text="Средний ВВП на душу населения",  # Подпись оси Y 1-го субграфика
    xaxis2_title_text="Год",
    yaxis2_title_text="Население",
    xaxis3_title_text="Континент",
    yaxis3_title_text="Продолжительность жизни",
    showlegend=False,  # Отключение показа легенды графика
    width=1000,  # Ширина
    height=500,  # Высота
)

#### Шаг 7. Добавим аннотации к линейному графику

In [32]:
fig.update_layout(
    # Массив словарей, каждый представляет собой одну аннотацию
    annotations=[
        # Первая аннотация для линии 'Europe'
        dict(  
            x=1980,
            y=550000000,  # x и y координаты для точки аннотации
            xref="x2",  # Укажем в `xref` и `yref` «x2» и «y2», чтобы и вторая линия отображалась 
            yref="y2",
            text="Europe",  # Текст аннотации для линии 'Europe'
            showarrow=True,  # Покажем «стрелку» с наконечником (`False` - без)
            arrowhead=1,  # Размер наконечника стрелки от 0 до 8
            ax=-30,  # Координаты смещения хвоста стрелки относительно точки назначения в пикселях
            ay=-30,
        ),
        # Вторая аннотация для линии 'Asia'
        dict(
            x=1980,
            y=2600000000,
            xref="x2",
            yref="y2",
            text="Asia",
            showarrow=True,
            arrowhead=1,
        ),
    ]
)

#### Шаг 8. Добавим аннотацию под всей фигурой

In [33]:
fig.add_annotation(
    dict(
        font=dict(color="black", size=12),  # Цвет и размер шрифта
        x=0,  # Положение аннотации
        y=-0.225,
        showarrow=False,
        text="Средний ВВП (слева); Средняя численность населения в Азии и Европе (по центру); Распределение средней ожидаемой продолжительности жизни (справа)",
        textangle=0,  # Поворот текста
        xanchor="left",
        xref="paper",  # Укажем в `xref` и `yref` значение 'paper', тем самым сделаем их абсолютными
        yref="paper",
    )
)

## 5.5 Экспорт в растровый и векторный форматы

DPI &ndash; *dots per inch* &ndash; разрешение нашего рисунка, количество точек на дюйм. Пришло из полиграфии. "Физический" размер рисунка может оставаться таким же, а изменение `dpi` приведет к изменению размера рисунка на бумаге или в документе. 300 dpi достаточно для печати. Рисунки, содержащие графики, желательно экспортировать в векторный формат, чтобы не страдало качество печати.  

В `plotly` нет явного параметра `dpi`, есть только размер в пикселах и параметр `scale`.
Необходимо установить пакет `kaleido`:

```bash
uv pip install -U kaleido
```

### Сохранение в растровый формат

In [34]:
fig.write_image('./data/population_gdp_life_expectancy.png', format='png')

In [35]:
fig.write_image('./data/population_gdp_life_expectancy_scaled_x2.png', scale=2)

### Сохранение в векторный формат

In [36]:
fig.write_image('./data/population_gdp_life_expectancy.svg')

### Экспорт в HTML

In [37]:
fig.write_html('./data/population_gdp_life_expectancy.html')

### `plotly` &leq; 6.1.1

> В более старой версии `plotly` (&leq; 6.1.1) можно было выбрать движок рендера. Для экспорта в векторный формат использовался `kaleido`, но определенной версии, см. [Not able to save plotly plots using to_image or write_image](https://stackoverflow.com/questions/70997997/not-able-to-save-plotly-plots-using-to-image-or-write-image).
> 
> Рабочая версия:
> ```bash
> pip install kaleido==0.1.0post1
> ```
> &nbsp;  
> И код экспорта немного отличался:
> ```python
> import plotly
> plotly.io.kaleido.scope.mathjax=None
> fig.write_image('./data/population_gdp_life_expectancy.png', format='png', engine='kaleido')
> ```  
> &nbsp;  
> В настоящее время `kaleido` используется в качестве основного движка, его API изменился. Некоторые сочетания версий `plotly` и `kaleido` не работали с Python 3.10, например.

## 5.6 Пример

Рассмотрим пример из 1 лекции.

### Датасет

[Goodreads Books - 31 Features](https://www.kaggle.com/datasets/austinreese/goodreads-books)

| Признак                | Описание                                                                                                    |
|------------------------|-------------------------------------------------------------------------------------------------------------|
| id                     | id книги                                                                                                    |
| title                  | Название книги                                                                                              |
| link                   | Ссылка на Goodreads                                                                                         |
| series                 | Название цикла, если книга является частью многоциклового произведения                                     |
| cover_link             | Ссылка на обложку книги                                                                                     |
| author                 | Список авторов книжного произведения                                                                        |
| author_link            | Ссылка на запись об авторах книжного произведения                                                           |
| rating_count           | Количество выставленных оценок на книжное произведение                                                      |
| review_count           | Количество оставленных отзывов на книжное произведение                                                      |
| average_rating         | Средняя оценка книжного произведения                                                                        |
| five_star_ratings      | Количество выставленных оценок на книжное произведение "5 звезд"                                            |
| four_star_ratings      | Количество выставленных оценок на книжное произведение "4 звезды"                                           |
| three_star_ratings     | Количество выставленных оценок на книжное произведение "3 звезды"                                           |
| two_star_ratings       | Количество выставленных оценок на книжное произведение "2 звезды"                                           |
| one_star_ratings       | Количество выставленных оценок на книжное произведение "1 звезда"                                           |
| number_of_pages        | Количество страниц в книжном произведении                                                                   |
| date_published         | Дата выхода книги в печатном издании                                                                        |
| publisher              | Название издательства                                                                                       |
| original_title         | Исходное название книги                                                                                     |
| genre_and_votes        | Список указанных пользователями жанров в виде <жанр1 N1>, <жанр2 N2>, где N1, N2 &ndash; количество "меток" |
| isbn                   | ISBN номер книжного произведения                                                                            |
| isbn13                 | 13-тизначный ISBN номер книжного произведения                                                               |
| asin                   | Amazon Standard Identification Number &ndash; артикул на площадке Amazon                                    |
| settings               | Место (или несколько), в котором происходят описываемые в книге события                                     |
| characters             | Имена основных персонажей в книге                                                                           |
| awards                 | Список названий присужденных книжному произведению премий (наград)                                          |
| amazon_redirect_link   | URL ссылка редиректа на площадку Amazon                                                                     |
| worldcat_redirect_link | URL ссылка редиректа на Goodread's WorldCat                                                                 |
| recommended_books      | Список id рекомендуемых книг с Goodreads                                                                    |
| books_in_series        | Список id книг, входящих в одноименный цикл                                                                 |
| description            | Синопсис                                                                                                    |

In [38]:
df = pd.read_csv('./../lecture_1/data/goodreads_books.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52199 entries, 0 to 52198
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      52199 non-null  int64
 1   title                   52199 non-null  str
 2   link                    52199 non-null  str
 3   series                  23319 non-null  str
 4   cover_link              51592 non-null  str
 5   author                  52199 non-null  str
 6   author_link             52199 non-null  str
 7   rating_count            52199 non-null  int64
 8   review_count            52199 non-null  int64
 9   average_rating          52199 non-null  float64
 10  five_star_ratings       52199 non-null  int64
 11  four_star_ratings       52199 non-null  int64
 12  three_star_ratings      52199 non-null  int64
 13  two_star_ratings        52199 non-null  int64
 14  one_star_ratings        52199 non-null  int64
 15  number_of_pages         49869 non-null  float64
 16  date_published          51339 non-null  str
 17  publisher               48563 non-null  str
 18  original_title          39250 non-null  str
 19  genre_and_votes         49359 non-null  str
 20  isbn                    40316 non-null  str
 21  isbn13                  39507 non-null  str
 22  asin                    5236 non-null   str
 23  settings                11515 non-null  str
 24  characters              13695 non-null  str
 25  awards                  10626 non-null  str
 26  amazon_redirect_link    52199 non-null  str
 27  worldcat_redirect_link  48214 non-null  str
 28  recommended_books       48205 non-null  str
 29  books_in_series         22078 non-null  str
 30  description             49624 non-null  str
dtypes: float64(2), int64(8), str(21)
memory usage: 12.3 MB

### Предобработка

#### Дропаем ненужные очевидные признаки

Уберем из датафрейма следующие признаки:
- `link`: ссылка на Goodreads
- `cover_link`: ссылка на обложку книги
- `author_link`: ссылка на запись об авторах книжного произведения
- `original_title`: исходное название книги
- `isbn`: ISBN номер книжного произведения
- `isbn13`: 13-тизначный ISBN номер книжного произведения
- `asin`: Amazon Standard Identification Number &ndash; артикул на площадке Amazon
- `settings`: место (или несколько), в котором происходят описываемые в книге события
- `amazon_redirect_link`: URL ссылка редиректа на площадку Amazon
- `worldcat_redirect_link`: URL ссылка редиректа на Goodread's WorldCat
- `recommended_books`: список id рекомендуемых книг с Goodreads
- `description`: описание книги

#### Вносимые модификации

Приводим датасет к аккуратному виду.

- `date_published`: парсим дату выхода в год, месяц, день
- `series`: извлекаем номер книги в цикле в новый признак, удаляем в текущем (оставляем только название)
- `books_in_series`: извлекаем количество книг в цикле в новый признак, удаляем текущий
- `awards`:
   + сплит строки в массив
   + применяем `.explode()`
   + извлекаем год присуждения премии в отдельный признак
   + переименовываем в `award`
- `author`: сплит строки в массив &rarr; `.explode()`
- `genre_and_votes`:
   + `NaN` &rarr; «Unknown»
   + сплит строки в массив
   + применяем `.explode()`
   + извлекаем количество проставленных тегов в новый признак, `NaN` &rarr; 0
   + убираем из `genre_and_votes` количество проставленных тегов
   + разделяем жанры и поджанры &ndash; меняем первое нахождение разделителя «-» на «, »
   + сплит с расширением в `genre` и `subgenre`
- `characters`: посчитаем количество персонажей в книге и переименуем в `characters_count`

In [39]:
import copy

def indent_string(text: str, indent_lvl: int = 1):
    message_formatted = copy.deepcopy(text)
    indent_string = '  ' * indent_lvl
    return indent_string + message_formatted

def iprint(text: str, indent_lvl: int = 0):
    print(indent_string(text, indent_lvl))

def preprocess_data(data: pd.DataFrame):
    data_new = copy.deepcopy(data)

    # Drop unneeded
    drop_list = ['link', 'cover_link', 'author_link', 'original_title', 'isbn', 'isbn13',
                 'asin', 'settings', 'amazon_redirect_link', 'worldcat_redirect_link', 
                   'recommended_books', 'description']
    data_new = data_new.drop(columns=drop_list)

    # Extract year
    feature = 'date_published'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN, drop", 2)

    data_new.drop(data_new[data_new[feature].isna()].index, inplace=True)

    iprint(f"New size: {data_new[feature].shape[0]}", 1)
    data_new.loc[:, 'year_published'] = data_new[feature].str.extract(r'(?<!\d)(-?\d{3,4})(?!\d)').to_numpy().flatten()

    digit_counts = lambda arr: np.floor(np.log10(arr.astype(int)) + 1e-9).astype(int) + 1

    iprint(f"Extract year:", 1)
    mask_nan = data_new['year_published'].isna()
    iprint(f"{data_new[mask_nan].shape[0]} out of {data_new['year_published'].shape[0]} is NaN", 2)

    data_new['year_published'] = data_new['year_published'].astype('Int32')
    mask_neg = data_new['year_published'] < 0
    mask_good = data_new['year_published'] > 0
    years_good = digit_counts(data_new[mask_good]['year_published'].to_numpy())

    iprint(f"{data_new[mask_neg].shape[0]} out of {data_new['year_published'].shape[0]} is negative", 2)
    iprint(f"{years_good[years_good == 4].shape[0]} is 4-digits", 2)
    iprint(f"{years_good[years_good == 3].shape[0]} is 3-digits", 2)

    data_new.drop(data_new[~mask_good].index, inplace=True)

    iprint(f"New size: {data_new[feature].shape[0]}", 2)

    # Extract month
    iprint(f"Extract month:", 1)
    import calendar
    month_list = list(calendar.month_name)[1:]
    data_new.loc[:, 'month_published'] = data_new[feature].str.extract(r'\b([a-zA-z]+)\b').to_numpy().flatten()
    mask_good = data_new['month_published'].isin(month_list)
    mask_nan = data_new['month_published'].isna()
    iprint(f"{data_new[mask_nan].shape[0]} out of {data_new['month_published'].shape[0]} is NaN", 2)
    iprint(f"{data_new[mask_good].shape[0]} out of {data_new['month_published'].shape[0]} is good", 2)

    # Extract  day
    iprint(f"Extract day:", 1)
    def get_ordinal_suffix(day):
        # 11, 12, 13 всегда имеют суффикс "th"
        if 11 <= day <= 13:
            return f"{day}th"
        # Для остальных смотрим на последнюю цифру
        return f"{day}" + {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")

    day_list = [get_ordinal_suffix(x) for x in range(1, 32)]

    data_new.loc[:, 'day_published'] = data_new[feature].str.extract(r'(?<!\w)( ?\d{1,2}[a-z]{1,2})(?!\w)').to_numpy().flatten()
    mask_good = data_new['day_published'].isin(day_list)
    mask_nan = data_new['day_published'].isna()
    iprint(f"{data_new[mask_nan].shape[0]} out of {data_new['day_published'].shape[0]} is NaN", 2)
    iprint(f"{data_new[mask_good].shape[0]} out of {data_new['day_published'].shape[0]} is good", 2)
    data_new.drop(columns=[feature], inplace=True)
    iprint(f"\"{feature}\" is dropped\n")

    # ----------

    feature = 'series'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN", 2)
    iprint("Removing curly brackets", 1)
    data_new['series'] = data_new['series'].str.strip('()')
    iprint(f"Extracting book in series order number into new \"{'book_in_series_num'}\"", 1)
    data_new.loc[:, 'book_in_series_num'] = data_new[feature].str.extract(r'#(\d{1,2})').to_numpy().flatten()
    data_new['book_in_series_num'] = data_new['book_in_series_num'].astype('Int32')
    iprint("Removing book in series order number\n", 1)
    data_new[feature] = data_new[feature].str.replace(r'( *#\d+ *)', '', regex=True)

    # ----------

    feature = 'books_in_series'
    iprint(f"\"{feature}\" preprocessing:")
    iprint(f"Adding \"{'books_in_series_count'}\"", 1)
    data_new['books_in_series_count'] = [len([idx for idx in x.split(',')])
                                         if pd.notna(x)
                                         else 0
                                         for x in data_new['books_in_series']]
    data_new['books_in_series_count'] += 1  # не забываем посчитать и саму книгу
    iprint("NaN check:", 2)
    iprint(f"{data_new[data_new['books_in_series_count'].isna()].shape[0]} out of {data_new['books_in_series_count'].shape[0]} is NaN", 3)
    data_new.drop(columns=[feature], inplace=True)
    iprint(f"\"{feature}\" is dropped\n", 1)

    # ----------
    
    feature = 'awards'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN", 2)
    iprint("Splitting data:", 1)
    len_before = data_new.shape[0]

    data_new[feature] = data_new[feature].str.split(pat=', ')
    data_new = data_new.explode(feature).reset_index(drop=True)
    len_after = data_new.shape[0]
    iprint(f"Count: {len_before} -> {len_after}", 2)
    iprint(f"Renaming \"{feature}\" into \"{'award'}\"", 1)
    data_new = data_new.rename(columns={feature: 'award'})

    # ----------

    feature = 'award'
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].notna()].shape[0]} out of {data_new[feature].shape[0]} is NOT NaN", 2)
    iprint("Extracting year into new \"award_year\"", 1)
    data_new.loc[:, 'award_year'] = data_new[feature].str.extract(r'(\d{3,4})').to_numpy().flatten()
    data_new['award_year'] = data_new['award_year'].astype('Int32')
    iprint("Removing year from \"award\"\n", 1)
    data_new[feature] = data_new[feature].str.replace(r' *\(\d+\) *', '', regex=True)

    # ----------

    feature = 'author'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN", 2)
    iprint("Splitting data:", 1)
    len_before = data_new.shape[0]
    
    data_new[feature] = data_new[feature].str.split(pat=', ')
    data_new = data_new.explode(feature).reset_index(drop=True)
    len_after = data_new.shape[0]
    iprint(f"Count: {len_before} -> {len_after}\n", 2)

    # ----------

    feature = 'genre_and_votes'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN", 2)
    iprint(f"NaN -> {'Unknown'}", 1)
    data_new[feature] = data_new[feature].fillna('Unknown')

    iprint("Splitting data:", 1)
    len_before = data_new.shape[0]
    data_new[feature] = data_new[feature].str.split(pat=', ')
    data_new = data_new.explode(feature).reset_index(drop=True)
    len_after = data_new.shape[0]
    iprint(f"Count: {len_before} -> {len_after}\n", 2)

    iprint(f"Extracting votes count into new \"{'genre_votes_count'}\"", 1)
    data_new.loc[:, 'genre_votes_count'] = data_new[feature].str.extract(r'\b(\d+)(?!\d)\b').to_numpy().flatten()
    iprint("NaN check:", 2)
    iprint(f"{data_new[data_new['genre_votes_count'].isna()].shape[0]} out of {data_new['genre_votes_count'].shape[0]} is NaN", 3)
    iprint(f"NaN -> {'Unknown'}", 2)
    data_new['genre_votes_count'] = data_new['genre_votes_count'].fillna(0)
    data_new['genre_votes_count'] = data_new['genre_votes_count'].astype(int)
    
    iprint("Removing votes count\n", 1)
    data_new[feature] = data_new[feature].str.replace(r'( *\d+ *)', '', regex=True)
    iprint("Replacing genre-subgenre delimiter", 1)
    data_new[feature] = data_new[feature].str.replace('-', ', ', 1)
    iprint("Splitting into \"genre\" and \"subgenre\"", 1)
    data_new = data_new.join(data_new[feature].str.split(pat=', ', expand=True).rename(columns={0: 'genre', 1: 'subgenre'}))
    data_new.drop(columns=[feature], inplace=True)
    iprint(f"\"{feature}\" is dropped\n", 1)

    # ----------

    feature = 'characters'
    iprint(f"\"{feature}\" preprocessing:")
    iprint("NaN check:", 1)
    iprint(f"{data_new[data_new[feature].isna()].shape[0]} out of {data_new[feature].shape[0]} is NaN", 2)
    iprint(f"Replacing feature with chars count", 1)
    data_new[feature] = [len([idx for idx in x.split(',')])
                         if pd.notna(x)
                         else 0
                         for x in data_new[feature]]
    data_new[feature] = data_new[feature].astype(int)
    iprint(f"Renaming \"{feature}\" into \"{'characters_count'}\"", 1)
    data_new = data_new.rename(columns={feature: 'characters_count'})

    # ----------

    iprint("Adding new feature:", 1)
    di = {1: 'Standalone', 2: 'Duology', 3: 'Trilogy'}
    data_new['series_type'] = data_new['books_in_series_count'].map(di).fillna('Saga')

    return data_new.reset_index(drop=True)

df_clean = preprocess_data(df)

"date_published" preprocessing:
  NaN check:
    860 out of 52199 is NaN, drop
  New size: 51339
  Extract year:
    28 out of 51339 is NaN
    75 out of 51339 is negative
    51187 is 4-digits
    49 is 3-digits
    New size: 51264
  Extract month:
    15410 out of 51264 is NaN
    35854 out of 51264 is good
  Extract day:
    18206 out of 51264 is NaN
    33058 out of 51264 is good
"date_published" is dropped

"series" preprocessing:
  NaN check:
    28224 out of 51264 is NaN
  Removing curly brackets
  Extracting book in series order number into new "book_in_series_num"
  Removing book in series order number

"books_in_series" preprocessing:
  Adding "books_in_series_count"
    NaN check:
      0 out of 51264 is NaN
  "books_in_series" is dropped

"awards" preprocessing:
  NaN check:
    40665 out of 51264 is NaN
  Splitting data:
    Count: 51264 -> 62978
  Renaming "awards" into "award"
  NaN check:
    22313 out of 62978 is NOT NaN
  Extracting year into new "award_year"
  Removing year from "award"

"author" preprocessing:
  NaN check:
    0 out of 62978 is NaN
  Splitting data:
    Count: 62978 -> 83674

"genre_and_votes" preprocessing:
  NaN check:
    3285 out of 83674 is NaN
  NaN -> Unknown
  Splitting data:
    Count: 83674 -> 412321

  Extracting votes count into new "genre_votes_count"
    NaN check:
      10406 out of 412321 is NaN
    NaN -> Unknown
  Removing votes count

  Replacing genre-subgenre delimiter
  Splitting into "genre" and "subgenre"
  "genre_and_votes" is dropped

"characters" preprocessing:
  NaN check:
    265475 out of 412321 is NaN
  Replacing feature with chars count
  Renaming "characters" into "characters_count"
  Adding new feature:

In [40]:
df_clean.head()

,id,title,series,author,rating_count,review_count,average_rating,five_star_ratings,four_star_ratings,three_star_ratings,...,year_published,month_published,day_published,book_in_series_num,books_in_series_count,award_year,genre_votes_count,genre,subgenre,series_type
0,630104,Inner Circle,Private,Kate Brian,7597,196,4.03,3045,2323,1748,...,2007,January,1st,5,11,<NA>,161,Young Adult,NaN,Saga
1,630104,Inner Circle,Private,Kate Brian,7597,196,4.03,3045,2323,1748,...,2007,January,1st,5,11,<NA>,45,Mystery,NaN,Saga
2,630104,Inner Circle,Private,Kate Brian,7597,196,4.03,3045,2323,1748,...,2007,January,1st,5,11,<NA>,32,Romance,NaN,Saga
3,630104,Inner Circle,Private,Julian Peploe,7597,196,4.03,3045,2323,1748,...,2007,January,1st,5,11,<NA>,161,Young Adult,NaN,Saga
4,630104,Inner Circle,Private,Julian Peploe,7597,196,4.03,3045,2323,1748,...,2007,January,1st,5,11,<NA>,45,Mystery,NaN,Saga

In [41]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 412321 entries, 0 to 412320
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     412321 non-null  int64
 1   title                  412321 non-null  str
 2   series                 192896 non-null  str
 3   author                 412321 non-null  str
 4   rating_count           412321 non-null  int64
 5   review_count           412321 non-null  int64
 6   average_rating         412321 non-null  float64
 7   five_star_ratings      412321 non-null  int64
 8   four_star_ratings      412321 non-null  int64
 9   three_star_ratings     412321 non-null  int64
 10  two_star_ratings       412321 non-null  int64
 11  one_star_ratings       412321 non-null  int64
 12  number_of_pages        404929 non-null  float64
 13  publisher              399376 non-null  str
 14  characters_count       412321 non-null  int64
 15  award                  164902 non-null  str
 16  year_published         412031 non-null  Int32
 17  month_published        289895 non-null  str
 18  day_published          267051 non-null  str
 19  book_in_series_num     181879 non-null  Int32
 20  books_in_series_count  412321 non-null  int64
 21  award_year             159112 non-null  Int32
 22  genre_votes_count      412321 non-null  int64
 23  genre                  412321 non-null  str
 24  subgenre               136858 non-null  str
 25  series_type            412321 non-null  str
dtypes: Int32(3), float64(2), int64(11), str(10)
memory usage: 78.3 MB

### График со слайдером

#### Сгруппируем оценки пользователей по годам выхода книжного издания

In [42]:
df_ratings = df_clean.groupby('year_published') \
    .agg({'rating_count' : 'sum',
          'five_star_ratings' : 'sum',
          'four_star_ratings': 'sum',
          'three_star_ratings': 'sum',
          'two_star_ratings': 'sum',
          'one_star_ratings': 'sum'}) \
    .reset_index().sort_values(by='year_published', ascending=True)
df_ratings.describe()

,year_published,rating_count,five_star_ratings,four_star_ratings,three_star_ratings,two_star_ratings,one_star_ratings
count,481.0,4.810000e+02,4.810000e+02,4.810000e+02,4.810000e+02,4.810000e+02,4.810000e+02
mean,1632.931393,7.214454e+07,3.648340e+07,2.114259e+07,1.016510e+07,2.784924e+06,1.568523e+06
std,407.459345,4.521712e+08,2.660446e+08,1.174442e+08,5.170899e+07,1.487914e+07,1.075165e+07
min,100.0,9.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1531.0,3.954500e+04,1.377600e+04,1.358400e+04,9.416000e+03,2.830000e+03,8.800000e+02
50%,1776.0,4.639440e+05,1.579530e+05,1.422200e+05,1.150120e+05,3.381600e+04,1.237500e+04
75%,1901.0,8.190340e+06,3.320849e+06,2.662727e+06,1.609036e+06,4.239060e+05,1.605600e+05
max,2021.0,7.521052e+09,4.834291e+09,1.745648e+09,6.630932e+08,2.257979e+08,1.802755e+08

#### Количество оценок переведем в %

In [43]:
ratings = ['five_star_ratings', 'four_star_ratings',
           'three_star_ratings', 'two_star_ratings',
           'one_star_ratings']

# show rating categories as a percentage
for ratings in ratings:
    df_ratings[ratings] = df_ratings[ratings] / df_ratings['rating_count'] * 100
df_ratings = df_ratings.reset_index(drop=True)
df_ratings.head()

,year_published,rating_count,five_star_ratings,four_star_ratings,three_star_ratings,two_star_ratings,one_star_ratings
0,100,298642,41.243696,34.135185,19.813690,3.825651,0.981778
1,121,231510,37.145264,37.566412,20.286381,3.738499,1.263444
2,125,107864,47.370763,33.672031,14.974412,3.166951,0.815842
3,150,40736,36.468971,33.641005,22.496072,5.705027,1.688924
4,162,27328,30.518150,32.406323,31.162178,4.888759,1.024590

In [44]:
fig_ratings = go.Figure()

fig_ratings.add_trace(
    go.Scatter(x=list(df_ratings.year_published),
               y=list(df_ratings.five_star_ratings), name = '★★★★★'))
fig_ratings.add_trace(
    go.Scatter(x=list(df_ratings.year_published),
               y=list(df_ratings.four_star_ratings), name = '★★★★'))
fig_ratings.add_trace(
    go.Scatter(x=list(df_ratings.year_published),
               y=list(df_ratings.three_star_ratings), name = '★★★'))
fig_ratings.add_trace(
    go.Scatter(x=list(df_ratings.year_published),
               y=list(df_ratings.two_star_ratings),name = '★★'))
fig_ratings.add_trace(
    go.Scatter(x=list(df_ratings.year_published),
               y=list(df_ratings.one_star_ratings), name = '★'))

# Set title
fig_ratings.update_layout(
    title_text="Средний пользовательский рейтинг",
    title_x=0.5,
    legend_title="Рейтинг",
    legend = dict(orientation = "v", y = .5, x = 1.025)
)

# Add range slider
fig_ratings.update_layout(
    xaxis = dict(
        rangeselector = dict(
            buttons = list([
                dict(count = 21,
                     label = "21y",
                     step = "year",
                     stepmode = "backward"),
                dict(count = 100,
                     label = "100y",
                     step = "year",
                     stepmode = "backward"),
                dict(step = "all")
            ])
        ),
        rangeslider = dict(
            visible = True
        ),
        type = "date"
    ),
    autosize=False,
    width=1000,
    height=800,
)

fig_ratings.show()

На графике какая-то аномалия в данных между точками «начало веков» и $1970$ годом.

In [45]:
df_ratings_filtered = df_ratings[df_ratings.year_published > 1100]

In [46]:
fig_ratings_filtered = go.Figure()

fig_ratings_filtered.add_trace(
    go.Scatter(x=list(df_ratings_filtered.year_published),
               y=list(df_ratings_filtered.five_star_ratings), name = '★★★★★'))
fig_ratings_filtered.add_trace(
    go.Scatter(x=list(df_ratings_filtered.year_published),
               y=list(df_ratings_filtered.four_star_ratings), name = '★★★★'))
fig_ratings_filtered.add_trace(
    go.Scatter(x=list(df_ratings_filtered.year_published),
               y=list(df_ratings_filtered.three_star_ratings), name = '★★★'))
fig_ratings_filtered.add_trace(
    go.Scatter(x=list(df_ratings_filtered.year_published),
               y=list(df_ratings_filtered.two_star_ratings),name = '★★'))
fig_ratings_filtered.add_trace(
    go.Scatter(x=list(df_ratings_filtered.year_published),
               y=list(df_ratings_filtered.one_star_ratings), name = '★'))

# Set title
fig_ratings_filtered.update_layout(
    title_text="Средний пользовательский рейтинг",
    title_x=0.5,
    legend_title="Рейтинг",
    legend = dict(orientation = "v", y = .5, x = 1.025)
)

# Add range slider
fig_ratings_filtered.update_layout(
    xaxis = dict(
        rangeselector = dict(
            buttons = list([
                dict(count = 21,
                     label = "21y",
                     step = "year",
                     stepmode = "backward"),
                dict(count = 100,
                     label = "100y",
                     step = "year",
                     stepmode = "backward"),
                dict(step = "all")
            ])
        ),
        rangeslider = dict(
            visible = True
        ),
        type = "date"
    ),
    autosize=False,
    width=1000,
    height=800,
)

fig_ratings_filtered.show()

### Топ-10 по количеству книг

В 1 лекции топ-10 жанров мы определяли так:

In [ ]:
genres = df_clean['genre'].explode().value_counts()
genres[:10]

Но так как в результате предобработки данных мы привели набор данных к аккуратному виду, у нас появились дубликаты:

In [ ]:
df_clean[df_clean['genre'] == 'Fiction']

Вычисленные статистики (`.sum()`, `.mean()` и т.п.) в таком случае будут содержать некорректные значения из-за дублирующихся строк в датафрейме.  

Если вам нужно узнать общую сумму признака (например, общую выручку), но строки продублированы, то перед вычислением суммы необходимо отфильтровать уникальные идентификаторы с использованием `.drop_duplicates()`:

In [ ]:
df_clean_uniq = df_clean.drop_duplicates(subset=['id'])
df_clean_uniq.groupby('id').agg({'rating_count': 'sum'}).reset_index().sort_values(by='rating_count', ascending=False)

Сравним с исходным датафреймом:

In [ ]:
df.groupby('id').agg({'rating_count': 'sum'}).reset_index().sort_values(by='rating_count', ascending=False)

Да, количество уникальных `id` в датафреймах разное из-за дропа строк, но для определенных `id` значения совпадают.  

Для сравнения пример некорректного получения статистик:

In [ ]:
df_clean.groupby('id') \
    .agg({'rating_count' : 'sum',
          'five_star_ratings' : 'sum',
          'four_star_ratings': 'sum',
          'three_star_ratings': 'sum',
          'two_star_ratings': 'sum',
          'one_star_ratings': 'sum'}) \
    .reset_index().sort_values(by='rating_count', ascending=False)

При этом вычисление статистики `nunique` будет корректным:

In [ ]:
genres = df_clean.groupby(['genre']) \
    .agg({'id' : 'nunique',
          'genre_votes_count' : 'sum'}) \
    .reset_index().sort_values(by='genre_votes_count', ascending=False)
genres

Сгруппируем данные в жанре `Fantasy` и посчитаем количество уникальных соавторов:

In [ ]:
df_gby = df_clean[df_clean.genre == 'Fantasy'].groupby(['id', 'genre']) \
    .agg({'author' : 'nunique'}) \
    .reset_index().sort_values(by='author', ascending=False)
df_gby

Ограничим 15-ю:

In [ ]:
df_gby[df_gby.author < 15]

Отфильтруем tidy-датасет по жанру и `id` книги:

In [ ]:
df_clean_one_book = df_clean[(df_clean.genre == 'Fantasy') & (df_clean.id == 3375878)]
df_clean_one_book

Видим множесто дублирующихся строчек. Посчитаем в группировке количество проставленных тегов:

In [ ]:
df_clean_one_book.groupby('genre').agg({'genre_votes_count': 'sum'}).reset_index().sort_values(by='genre_votes_count', ascending=False)

А должно быть $165 + 14 + 9 = 188$. Три поджанра и 14 авторов дают нам именно эти 42 дубликата (14 дублей для суммы оценок): $188 * 14 = 2632$.

##### Топ-10 жанров

In [ ]:
genres = df_clean_uniq.groupby('genre') \
    .agg({'id': 'count',
          'genre_votes_count': 'sum',
          'rating_count' : 'sum',
          'five_star_ratings' : 'sum',
          'four_star_ratings': 'sum',
          'three_star_ratings': 'sum',
          'two_star_ratings': 'sum',
          'one_star_ratings': 'sum'}) \
    .reset_index().sort_values(by='rating_count', ascending=False)[:10]

genres

##### Топ-10 поджанров

In [ ]:
subgenres = df_clean_uniq.groupby('subgenre') \
    .agg({'id': 'count',
          'genre_votes_count': 'sum',
          'rating_count' : 'sum',
          'five_star_ratings' : 'sum',
          'four_star_ratings': 'sum',
          'three_star_ratings': 'sum',
          'two_star_ratings': 'sum',
          'one_star_ratings': 'sum'}) \
    .reset_index().sort_values(by='rating_count', ascending=False)[:10]

subgenres

##### Топ-10 авторов

In [ ]:
authors = df_clean_uniq.groupby('author') \
    .agg({'id': 'count',
          'genre_votes_count': 'sum',
          'rating_count' : 'sum',
          'five_star_ratings' : 'sum',
          'four_star_ratings': 'sum',
          'three_star_ratings': 'sum',
          'two_star_ratings': 'sum',
          'one_star_ratings': 'sum'}) \
    .reset_index().sort_values(by='id', ascending=False)[:10]

authors

In [ ]:
fig_top10 = make_subplots(rows=1, cols=3,
                      specs=[[{'type': 'xy'}, {"type": "xy"}, {"type": "xy"}]],
                      subplot_titles=("Топ 10 самых популярных жанров",
                                      "Топ 10 самых популярных авторов",
                                      "Топ 10 самых популярных поджанров"))
fig_top10.add_trace(go.Bar(x=genres.genre,
                       y=genres['rating_count'],
                       hovertemplate='<b>Количество оценок</b><br>' +
                                     '%{x} 👉 %{y}' +
                                     "<extra></extra>",
                       marker_color=px.colors.sequential.Plasma),
                       row=1, col=1)
fig_top10.add_trace(go.Bar(x=authors.author,
                       y=authors['rating_count'],
                       hovertemplate='<b>Количество оценок</b><br>' +
                                     '%{x} 👉 %{y}' +
                                     "<extra></extra>",
                       marker_color=px.colors.sequential.Plotly3),
                       row=1, col=2)
fig_top10.add_trace(go.Bar(x=subgenres.subgenre,
                       y=subgenres['rating_count'],
                       hovertemplate='<b>Количество оценок</b><br>' +
                                     '%{x} 👉 %{y}' +
                                     "<extra></extra>",
                       marker_color=px.colors.sequential.Plasma),
                       row=1, col=3)
fig_top10.update_traces(marker_line_width=0)

fig_top10.update_layout(showlegend=False,
                        plot_bgcolor='rgba(0,0,0,0)',
                        font=dict(family='Arial',
                                  size=12,
                                  color='black'),
                        autosize=False,
                        title='Топ-10 по количеству проставленных оценок',
                        title_x=0.5,
                        width=1100,
                        height=600,)

fig_top10.show()

### Топ 10 издательств по количеству оценок в жанре

In [ ]:
df_grouped_by_pub = df_clean_uniq.groupby(['publisher', 'genre']) \
    .agg({'title':'count',
          'average_rating':'mean',
          'rating_count': 'sum'}) \
    .reset_index()

In [ ]:
df_pub_popular = df_grouped_by_pub.sort_values(by=['rating_count'], ascending=False)
df_pub_popular

Нам потребуется функция `interact` из [Jupyter Widgets &rarr; Using Interact](https://ipywidgets.readthedocs.io/en/8.1.2/examples/Using%20Interact.html).  

Данная функция создает виджет с контролами. По клику в выпадающем списке вызывается автоматом `barplot_by_genre` и перерисовывает график:

In [ ]:
from ipywidgets import interact, fixed, widgets
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

def barplot_by_genre(genre, df):
    mask = [genre in x for x in df['genre']]
    newframe = df[mask]
    df_grouped_by_pub = newframe.groupby('publisher') \
       .agg({'title':'count', 'average_rating':'mean', 'rating_count': 'sum'}) \
       .reset_index()
    df_popular = df_grouped_by_pub.sort_values(by=['rating_count'], ascending=False)[:10]
    barplot = px.bar(data_frame = df_popular,
                     x = 'publisher',
                     y = 'rating_count',
                     labels = {'publisher': 'Издательство', 'rating_count': 'Количество оценок', 'average_rating': 'Рейтинг'},
                     color = 'average_rating',
                     opacity = 0.9,
                     orientation = 'v',
                     barmode = 'relative',
                     title = f"Топ 10 издательств по количеству оценок в жанре \"{genre}\"",
                    )
    barplot.layout.update(autosize=False,
                          width=1000,
                          height=500,
                          title_x = 0.5)
    barplot
    barplot.show()

In [ ]:
genres.genre

In [ ]:
interact(barplot_by_genre, genre=genres.genre.to_list(), df=fixed(df_pub_popular));

### Связь рейтинга книги с количеством страниц и количеством сиквелов

In [ ]:
series_type_anno = [('Любая', 'All'), ('Отдельная', 'Standalone'),
                    ('Дилогия', 'Duology'), ('Трилогия', 'Trilogy'),
                    ('Цикл', 'Saga')]
series_type_dict = dict()
for t in series_type_anno:
    series_type_dict[t[1]] = t[0]

toggle = widgets.ToggleButtons(options=series_type_anno,
                               description='Цикличность:',
                               disabled=False,
                               button_style='',
                               tooltips=['Любое количество книг',
                                        'Отдельная книга',
                                        'Две книги в цикле',
                                        'Три книги в цикле',
                                        'Больше книг богу книг']
                                )
def making_pages(df, toggle, label, year_f):
    df_pages = df[df['number_of_pages'] <= 1500].copy()
    if not toggle == 'All':
        mask = [toggle in x for x in df_pages['series_type']]
        colour = 'rating_count'
    else:
        mask = [True for x in df_pages['series_type']]
        colour = 'series_type'
    title = f"Зависимость рейтинга от количества страниц для цикличности \"{label}\""
    fig = px.scatter(df_pages[mask],
                     x="number_of_pages",
                     y="rating_count",
                     labels = {"number_of_pages": 'Количество страниц', "rating_count": 'Количество оценок',
                               "review_count": 'Количество рецензий', "series_type": 'Цикличность'},
                     size='review_count',
                     color="review_count",
                     hover_data=['title', 'author'],
                     facet_col="series_type",
                     title = title
                    )
    # Меняем названия subplot'ов
    fig.for_each_annotation(lambda a: a.update(text = series_type_dict[a.text.split('=')[1]]))
    # Меняем названия рядов в легенде
    # fig.for_each_trace(lambda t: t.update(name = series_type_dict[t.name],
    #                                       legendgroup = series_type_dict[t.name],
    #                                       hovertemplate = t.hovertemplate.replace(t.name, series_type_dict[t.name.split('=')[1]])
    #                                      ) if t.name != '' else '')

    fig.layout.update(autosize=False,
                      width=1300,
                      height=400,
                      title_x = 0.5)
    fig.show()

    df_scat = df_pages[mask].groupby(['year_published', 'series_type']) \
        .agg({'average_rating' : 'mean',
              'rating_count' : 'sum',
              'review_count' : 'sum'}) \
        .reset_index()
    df_scat = df_scat[df_scat.year_published > year_f]
    title = f"Средняя оценка для цикличности \"{label}\" c {year_f} по 2021 гг."
    fig = px.scatter(df_scat,
                     y="average_rating",
                     x="year_published",
                     labels = {"average_rating": 'Средняя оценка', "year_published": 'Год выхода', "series_type": 'Цикличность', "rating_count": 'Количество оценок'},
                     log_x=True,
                     log_y=True,
                     color=colour,
                     size="rating_count",
                     title = title)
    fig.layout.update(autosize=False,
                      width=1000,
                      height=400,
                      title_x = 0.5)
    fig.show()

In [ ]:
interact(making_pages, toggle = toggle, label = toggle.label, df=fixed(df_clean_uniq), year_f=fixed(1500));

## 5.7 `Plotly Dash`

Источники:
- [A Minimal Dash App](https://dash.plotly.com/minimal-app)
- [Dash in Jupyter Environments](https://dash.plotly.com/dash-in-jupyter)
- [Dash Example Index]()

`Dash` &ndash; библиотека для создания интерактивных веб-приложений и дашбордов.

> ```bash
> uv pip install -U dash
> ```

### Интерактивный график с использованием `Dash`

In [ ]:
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go
import pandas as pd

app = Dash(__name__)

app.layout = html.Div(
    [
        html.H2(
            "Средний пользовательский рейтинг",
            style={
                'text-align': 'center',
                'font-family': 'Ink Free'
            }
        ),
        
        html.Div(
            [
                html.Br(),
                dcc.Checklist(
                    id="toggle-rangeslider",
                    options=[{"label": " Слайдер «Год выхода»", "value": "slider"}],
                    value=["slider"],
                    style={
                        'font-family': 'Tiger Expert',
                        'font-weight': 'bold',
                        'text-align': 'left'
                    }
                ),
                html.Br(),
                dcc.Graph(
                    id="graph",
                    style={
                        'font-weight': 'bold',
                        'font-size': '24'
                    }
                )
            ],
            style={
                "display": "flex", 
                'align-items': 'left',
                'flex-direction': 'column'
            }
        ),
    ], style={
        'background-color': 'rgba(180, 180, 180, 0.5)',
        'display': 'flex',
        'align-items': 'center',
        'flex-direction': 'column'
    }
)


@app.callback(
    Output("graph", "figure"),
    Input("toggle-rangeslider", "value"),
)
def display_scatter(value):
    fig_1 = go.Figure()

    fig_1.add_trace(
        go.Scatter(x=list(df_ratings.year_published),
                   y=list(df_ratings.five_star_ratings), name = '★★★★★'))
    fig_1.add_trace(
        go.Scatter(x=list(df_ratings.year_published),
                   y=list(df_ratings.four_star_ratings), name = '★★★★'))
    fig_1.add_trace(
        go.Scatter(x=list(df_ratings.year_published),
                   y=list(df_ratings.three_star_ratings), name = '★★★'))
    fig_1.add_trace(
        go.Scatter(x=list(df_ratings.year_published),
                   y=list(df_ratings.two_star_ratings),name = '★★'))
    fig_1.add_trace(
        go.Scatter(x=list(df_ratings.year_published),
                   y=list(df_ratings.one_star_ratings), name = '★'))

    # Set title
    fig_1.update_layout(
        # title_text="Средний пользовательский рейтинг",
        title_x=0.5,
        legend_title="Рейтинг",
        legend = dict(orientation = "v", y = .5, x = 1.025),
        font_family = 'Ink Free'
    )

    # Add range slider
    fig_1.update_layout(
        xaxis = dict(
            rangeselector = dict(
                buttons = list([
                    dict(count = 21,
                         label = "21y",
                         step = "year",
                         stepmode = "backward"),
                    dict(count = 100,
                         label = "100y",
                         step = "year",
                         stepmode = "backward"),
                    dict(step = "all")
                ])
            ),
            rangeslider = dict(
                visible = "slider" in value
            ),
            type = "date"
        ),
        autosize=False,
        width=1000,
        height=800,
    )

    return  fig_1


if __name__ == "__main__":
    app.run(debug=True, mode='jupyterlab')